# Read the documentation: https://github.com/1up-lab/OneupFlysystemBundle
oneup_flysystem:
    adapters:
        default:
            local:
                location: '%kernel.project_dir%/var/files'
    filesystems:
        default:
            adapter: default
            mount: default
