version: '3.2'

services:
  php:
    image: inshopgroup/docker-inshop-crm-api-php-fpm-dev:php8.1
    depends_on:
      - db
    env_file:
      - ./.env
    volumes:
      - api-data:/var/www
    networks:
      - api

  nginx:
    image: inshopgroup/docker-inshop-crm-api-nginx-prod:latest
    depends_on:
      - php
    volumes:
      - api-data:/var/www
    ports:
      - ${PORT_API}:80
    networks:
      - api

  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    volumes:
      - db-data:/var/lib/postgresql/data:rw
    ports:
      - ${PORT_DATABASE}:5432
    networks:
      - api

volumes:
  db-data: {}
  api-data:
    external: true

networks:
    api:
