#controllers:
#    resource: ../src/Controller/
#    type: attribute

login:
    path: /login
    methods:  [POST]

client_login:
    path: /frontend/login
    methods:  [POST]

gesdinet_jwt_refresh_token:
    path:     /frontend/token/refresh
    defaults: { _controller: gesdinet.jwtrefreshtoken:refresh }
